### ISSUE TITLE
Create option to turn on flash in scanner

### ISSUE THREAD

**Issue by wkmeijer** [digital-voting-pass/digital-voting-pass-app#124]
Create a button that enables or disabled flash to be able to better scan in a dark environment.

**Comment by wkmeijer** [comment]
When torch is on before starting 'scan travel document' this activity does not start and the following exception is thrown:
06-13 23:13:09.560 31696-31696/? I/SensorManagerFlow: registerListenerImpl
                                                      java.lang.Exception
                                                          at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:118)
                                                          at android.hardware.SensorManager.registerListener(SensorManager.java:775)
                                                          at android.hardware.SensorManager.registerListener(SensorManager.java:682)
                                                          at android.view.OrientationEventListener.enable(OrientationEventListener.java:93)
                                                          at com.digitalvotingpass.camera.Camera2BasicFragment$1.onSurfaceTextureAvailable(Camera2BasicFragment.java:142)
                                                          at android.view.TextureView.getHardwareLayer(TextureView.java:370)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14187)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.View.draw(View.java:15016)
                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3413)
                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14205)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.View.draw(View.java:15016)
                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3413)
                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
                                                          at android.view.View.draw(View.java:15291)
                                                          at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14210)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.View.draw(View.java:15016)
                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3413)
                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14205)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.View.draw(View.java:15016)
                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3413)
                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14205)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.View.draw(View.java:15016)
                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3413)
                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3204)
                                                          at android.view.View.draw(View.java:15291)
                                                          at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2698)
                                                          at android.view.View.updateDisplayListIfDirty(View.java:14210)
                                                          at android.view.View.getDisplayList(View.java:14232)
                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:287)
                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:293)
                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:341)
                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2574)
                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2390)
                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2008)
                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6037)
                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:606)
                                                          at android.view.Choreographer.doFrame(Choreographer.java:575)
                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5569)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)

**Comment by wkmeijer** [comment]
The bug seems to be device specfic as only I (Huawei P7) have this bug. It is similar to an issue I found on stackoverflow: https://stackoverflow.com/questions/37723740/cordova-plugin-device-motion-exception-in-start-method

Since it probably is a hardware issue we won't try to fix it.
