### ISSUE TITLE
Illegal derived key error in blockchain init

### ISSUE THREAD

**Issue by jonathanraes** [digital-voting-pass/digital-voting-pass-app#144]

**Comment by wkmeijer** [comment]
```
06-16 15:40:35.470 24918-24941/? E/AndroidRuntime: FATAL EXCEPTION: WalletAppKit STARTING
                                                   Process: com.digitalvotingpass.digitalvotingpass, PID: 24918
                                                   org.bitcoinj.crypto.HDDerivationException: Illegal derived key: I_L >= n
                                                       at org.bitcoinj.crypto.HDKeyDerivation.assertLessThanN(HDKeyDerivation.java:227)
                                                       at org.bitcoinj.crypto.HDKeyDerivation.deriveChildKeyBytesFromPublic(HDKeyDerivation.java:190)
                                                       at org.bitcoinj.wallet.DeterministicKeyChain.checkForBitFlip(DeterministicKeyChain.java:512)
                                                       at org.bitcoinj.wallet.DeterministicKeyChain.getKeys(DeterministicKeyChain.java:501)
                                                       at org.bitcoinj.wallet.KeyChainGroup.freshKeys(KeyChainGroup.java:221)
                                                       at org.bitcoinj.wallet.Wallet.freshKeys(Wallet.java:480)
                                                       at org.bitcoinj.wallet.Wallet.freshKey(Wallet.java:464)
                                                       at org.bitcoinj.wallet.Wallet.freshReceiveKey(Wallet.java:495)
                                                       at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:366)
                                                       at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:271)
                                                       at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
                                                       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
                                                       at java.lang.Thread.run(Thread.java:831)
```

**Comment by wkmeijer** [comment]
Exception occurs when the DigitalVotingPass folder is removed from the phone and the app is restarted.

**Comment by wkmeijer** [comment]
`06-16 16:37:52.670 32041-32064/? E/AndroidRuntime: FATAL EXCEPTION: WalletAppKit STARTING
                                                   Process: com.digitalvotingpass.digitalvotingpass, PID: 32041
                                                   java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/DigitalVotingPass/wallet-1593964000.tmp: open failed: EACCES (Permission denied)
                                                       at com.google.common.base.Throwables.propagate(Throwables.java:160)
                                                       at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:58)
                                                       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
                                                       at java.lang.Thread.run(Thread.java:831)
                                                    Caused by: java.io.FileNotFoundException: /storage/emulated/0/DigitalVotingPass/wallet-1593964000.tmp: open failed: EACCES (Permission denied)
                                                       at libcore.io.IoBridge.open(IoBridge.java:463)
                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:76)
                                                       at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1302)
                                                       at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1343)
                                                       at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:374)
                                                       at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:271)
                                                       at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
                                                       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) 
                                                       at java.lang.Thread.run(Thread.java:831) 
                                                    Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                       at libcore.io.Posix.open(Native Method)
                                                       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                       at libcore.io.IoBridge.open(IoBridge.java:449)
                                                       at java.io.FileOutputStream.<init>(FileOutputStream.java:76) 
                                                       at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1302) 
                                                       at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1343) 
                                                       at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:374) 
                                                       at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:271) 
                                                       at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54) 
                                                       at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) 
                                                       at java.lang.Thread.run(Thread.java:831) 
`
