### ISSUE TITLE
App behavior undefined when blockchain changes 

### ISSUE THREAD

**Issue by jonathanraes** [digital-voting-pass/digital-voting-pass-app#87]
The app assumes the network parameters. What happens if these are no longer valid?

**Comment by landgenoot** [comment]
It crashes with:
```
15:48:35.164 [NioClientManager] INFO  org.bitcoinj.core.PeerGroup - [188.226.149.56]:6799: Peer died      (0 connected, 0 pending, 1 max)
15:48:35.169 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup - Peer discovery took 77.62 μs and returned 0 items
15:48:35.171 [PeerGroup Thread] INFO  org.bitcoinj.core.PeerGroup - Waiting 599999 msec before next connect attempt to [188.226.149.56]:6799
15:48:35.175 [NioClientManager] WARN  org.bitcoinj.net.NioClientManager - Failed to connect with exception: java.nio.channels.ClosedChannelException: null
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:721) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64) ~[na:0.0]
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) ~[na:0.0]
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) ~[na:0.0]
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:51) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:762) ~[na:0.0]
```

And it just starts up without this peer.

Maybe add a notification if it cannot connect to any of the peers?
